import os
import html
from datetime import datetime
from typing import Optional, List, Tuple
from pathlib import Path
from PIL import Image as PILImage
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas
from app.core.config import settings
from app.core.logging import logger
from app.models.inspection import Inspection

def sanitize_pdf_text(text: Optional[str]) -> str:
    """Sanitizes text for ReportLab Paragraphs, replacing unsupported Unicode like INR symbol."""
    if text is None:
        return ""
    s = str(text)
    # Replace Rupee symbol with Rs.
    s = s.replace("\u20b9", "Rs. ").replace("₹", "Rs. ")
    # Escape HTML special chars while preserving allowed tags
    s = html.escape(s, quote=False)
    # Restore basic formatting tags if present in input
    s = s.replace("&lt;b&gt;", "<b>").replace("&lt;/b&gt;", "</b>")
    s = s.replace("&lt;i&gt;", "<i>").replace("&lt;/i&gt;", "</i>")
    s = s.replace("&lt;font", "<font").replace("&lt;/font&gt;", "</font>").replace("&gt;", ">")
    return s

class NumberedCanvas(canvas.Canvas):
    """Canvas that performs two passes to accurately render 'Page X of Y' in the footer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header line & title (pages > 1)
        if self._pageNumber > 1:
            self.drawString(36, 810, "LabelLens Statutory Metrology Audit Report")
            self.drawRightString(559, 810, datetime.utcnow().strftime("%d-%b-%Y"))
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(36, 804, 559, 804)

        # Footer
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(559, 24, page_text)
        self.drawString(36, 24, "CONFIDENTIAL & STATUTORY &middot; Generated by LabelLens AI Metrology Suite")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(36, 34, 559, 34)
        self.restoreState()

class CompliancePDFReportGenerator:
    """
    Generates official, government-grade Legal Metrology inspection audit reports in PDF format
    with support for arbitrary multi-photo evidence packages.
    """

    @classmethod
    def _compute_image_dimensions(cls, img_path: str, max_w: float = 240, max_h: float = 150) -> Tuple[float, float]:
        """Calculates scale-preserving width and height for embedding photos in PDF."""
        try:
            with PILImage.open(img_path) as im:
                orig_w, orig_h = im.size
                if orig_w <= 0 or orig_h <= 0:
                    return max_w, max_h
                ratio = min(max_w / orig_w, max_h / orig_h)
                return max(40, round(orig_w * ratio, 1)), max(40, round(orig_h * ratio, 1))
        except Exception:
            return max_w, max_h

    @classmethod
    def generate(cls, inspection: Inspection, output_path: Optional[str] = None) -> str:
        if output_path is None:
            output_path = str(settings.REPORTS_DIR / f"Inspection_Report_{inspection.id}.pdf")

        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            leftMargin=36,
            rightMargin=36,
            topMargin=36,
            bottomMargin=42
        )

        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#0F172A")
        )
        
        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#64748B")
        )

        section_heading = ParagraphStyle(
            'SectionHeading',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=15,
            textColor=colors.HexColor("#1E293B"),
            spaceBefore=12,
            spaceAfter=6
        )

        body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8.5,
            leading=11.5,
            textColor=colors.HexColor("#334155")
        )

        bold_label = ParagraphStyle(
            'BoldLabel',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8.5,
            leading=11.5,
            textColor=colors.HexColor("#1E293B")
        )

        disclaimer_style = ParagraphStyle(
            'DisclaimerText',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=7.5,
            leading=10,
            textColor=colors.HexColor("#64748B")
        )

        story = []

        # 1. Header Banner
        report_date_str = inspection.created_at.strftime('%d-%b-%Y %H:%M UTC') if inspection.created_at else datetime.utcnow().strftime('%d-%b-%Y %H:%M UTC')
        header_data = [
            [
                Paragraph("<b>LabelLens</b> Legal Metrology Compliance Audit", title_style),
                Paragraph(f"<b>Audit ID:</b> {inspection.id[:8].upper()}<br/><b>Date:</b> {report_date_str}", subtitle_style)
            ]
        ]
        header_table = Table(header_data, colWidths=[340, 180])
        header_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ]))
        story.append(header_table)
        story.append(Spacer(1, 6))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#CBD5E1"), spaceAfter=8))

        # 2. Overall Status Banner
        status_colors = {
            "COMPLIANT": colors.HexColor("#10B981"),
            "NON_COMPLIANT": colors.HexColor("#EF4444"),
            "NEEDS_REVIEW": colors.HexColor("#F59E0B"),
            "UNABLE_TO_VERIFY": colors.HexColor("#64748B")
        }
        status_bg = {
            "COMPLIANT": colors.HexColor("#ECFDF5"),
            "NON_COMPLIANT": colors.HexColor("#FEF2F2"),
            "NEEDS_REVIEW": colors.HexColor("#FFFBEB"),
            "UNABLE_TO_VERIFY": colors.HexColor("#F1F5F9")
        }
        
        status_val = (inspection.overall_status or "PENDING").upper()
        badge_color = status_colors.get(status_val, colors.HexColor("#3B82F6"))
        badge_bg = status_bg.get(status_val, colors.HexColor("#F8FAFC"))

        status_text = f"<font size=13 color='{badge_color.hexval()}'><b>VERDICT: {status_val.replace('_', ' ')}</b></font>"
        score_text = f"<b>Compliance Index:</b> {inspection.compliance_score:.1f}%" if inspection.compliance_score is not None else ""
        category_clean = (inspection.product_category or "packaged_commodity").replace('_', ' ').title()
        
        summary_table_data = [
            [
                Paragraph(status_text, bold_label),
                Paragraph(score_text, subtitle_style),
                Paragraph(f"<b>Category:</b> {category_clean}", subtitle_style)
            ]
        ]
        summary_table = Table(summary_table_data, colWidths=[200, 160, 160])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), badge_bg),
            ('BOX', (0, 0), (-1, -1), 1, badge_color),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 8))

        # 3. Product & Multi-Panel Summary Metadata
        panel_count = len(inspection.images) if inspection.images else 1
        primary_quality = inspection.image.quality_status if inspection.image else "PASS"
        img_meta = [
            [
                Paragraph("<b>Product Name:</b>", bold_label),
                Paragraph(sanitize_pdf_text(inspection.product_name or "Packaged Commodity"), body_style),
                Paragraph("<b>Panels / Photos:</b>", bold_label),
                Paragraph(f"{panel_count} Photo(s) Analyzed", body_style)
            ],
            [
                Paragraph("<b>Execution Mode:</b>", bold_label),
                Paragraph(inspection.execution_mode or "LIVE_PIPELINE", body_style),
                Paragraph("<b>Quality Verdict:</b>", bold_label),
                Paragraph(primary_quality, body_style)
            ]
        ]
        meta_table = Table(img_meta, colWidths=[110, 150, 110, 150])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ('PADDING', (0, 0), (-1, -1), 4),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 8))

        # Panel Breakdown Table if multi-panel
        if len(inspection.images) > 1:
            panel_data = [
                [
                    Paragraph("<b>#</b>", bold_label),
                    Paragraph("<b>Panel Role / Tag</b>", bold_label),
                    Paragraph("<b>File Name</b>", bold_label),
                    Paragraph("<b>Dimensions</b>", bold_label),
                    Paragraph("<b>Sharpness</b>", bold_label),
                    Paragraph("<b>Quality</b>", bold_label)
                ]
            ]
            for idx, img in enumerate(inspection.images):
                p_label = (img.panel_type or f"Photo {idx+1}").replace('_', ' ').title()
                panel_data.append([
                    Paragraph(str(idx + 1), body_style),
                    Paragraph(f"<b>{p_label}</b>", body_style),
                    Paragraph(sanitize_pdf_text(img.original_filename), body_style),
                    Paragraph(f"{img.width or '—'}x{img.height or '—'}", body_style),
                    Paragraph(f"{img.blur_score:.1f}" if img.blur_score is not None else "—", body_style),
                    Paragraph(f"<b>{img.quality_status}</b>", body_style)
                ])
            panel_tbl = Table(panel_data, colWidths=[25, 115, 160, 80, 65, 75])
            panel_tbl.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ('PADDING', (0, 0), (-1, -1), 3),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            story.append(panel_tbl)
            story.append(Spacer(1, 8))

        # 4. Multi-Image Visual Evidence (Independent Flowable Rows for Safe Pagination)
        images_to_embed = []
        for idx, img in enumerate(inspection.images):
            target_p = img.annotated_file_path if (img.annotated_file_path and os.path.exists(img.annotated_file_path)) else (
                img.file_path if (img.file_path and os.path.exists(img.file_path)) else None
            )
            p_label = (img.panel_type or f"Photo {idx+1}").replace('_', ' ').title()
            if target_p:
                images_to_embed.append((p_label, target_p))

        if images_to_embed:
            story.append(Paragraph("Visual Inspection Evidence & Bounding Boxes", section_heading))
            
            if len(images_to_embed) == 1:
                p_label, p_path = images_to_embed[0]
                try:
                    w, h = cls._compute_image_dimensions(p_path, max_w=460, max_h=230)
                    single_cell = [
                        Paragraph(f"<b>Evidence: {p_label}</b>", subtitle_style),
                        Spacer(1, 3),
                        RLImage(p_path, width=w, height=h)
                    ]
                    single_tbl = Table([[single_cell]], colWidths=[520])
                    single_tbl.setStyle(TableStyle([
                        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                        ('PADDING', (0, 0), (-1, -1), 4),
                        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1"))
                    ]))
                    story.append(single_tbl)
                    story.append(Spacer(1, 10))
                except Exception as e:
                    logger.warning(f"Could not embed single image in PDF: {e}")
            else:
                # 2-column image rows, each row wrapped individually
                for i in range(0, len(images_to_embed), 2):
                    row_items = images_to_embed[i:i+2]
                    row_cells = []
                    for p_label, p_path in row_items:
                        try:
                            w, h = cls._compute_image_dimensions(p_path, max_w=240, max_h=150)
                            cell_content = [
                                Paragraph(f"<b>Panel / Angle: {p_label}</b>", subtitle_style),
                                Spacer(1, 2),
                                RLImage(p_path, width=w, height=h)
                            ]
                            row_cells.append(cell_content)
                        except Exception as img_e:
                            logger.warning(f"Could not load image {p_path}: {img_e}")
                            row_cells.append([Paragraph(f"<b>{p_label}:</b> [Image Unavailable]", subtitle_style)])
                    
                    while len(row_cells) < 2:
                        row_cells.append("")

                    row_tbl = Table([row_cells], colWidths=[260, 260])
                    row_tbl.setStyle(TableStyle([
                        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                        ('PADDING', (0, 0), (-1, -1), 4),
                        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                    ]))
                    story.append(KeepTogether([row_tbl, Spacer(1, 6)]))

                story.append(Spacer(1, 6))

        # 5. Declarations & Compliance Matrix
        story.append(Paragraph("Mandatory Declarations & Compliance Checks", section_heading))
        
        checks_data = [
            [
                Paragraph("<b>Declaration / Field</b>", bold_label),
                Paragraph("<b>Detected Value</b>", bold_label),
                Paragraph("<b>Status</b>", bold_label),
                Paragraph("<b>Conf.</b>", bold_label),
                Paragraph("<b>Legal Reference & Reason</b>", bold_label)
            ]
        ]

        for check in inspection.compliance_checks:
            stat_color = colors.HexColor("#10B981") if check.status == "PASS" else (
                colors.HexColor("#EF4444") if check.status in ["FAIL", "NOT_DETECTED"] else colors.HexColor("#F59E0B")
            )
            conf_str = f"{int(check.confidence * 100)}%" if check.confidence else "—"
            det_val = sanitize_pdf_text(check.detected_value) or "<i>[Not Detected]</i>"
            
            checks_data.append([
                Paragraph(f"<b>{sanitize_pdf_text(check.rule_title)}</b>", body_style),
                Paragraph(det_val, body_style),
                Paragraph(f"<font color='{stat_color.hexval()}'><b>{check.status}</b></font>", body_style),
                Paragraph(conf_str, body_style),
                Paragraph(f"<font size=7.5><b>{sanitize_pdf_text(check.legal_reference or '')}</b><br/>{sanitize_pdf_text(check.explanation)}</font>", body_style)
            ])

        checks_table = Table(checks_data, colWidths=[115, 105, 60, 45, 195])
        checks_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ('PADDING', (0, 0), (-1, -1), 3.5),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")])
        ]))
        story.append(checks_table)
        story.append(Spacer(1, 10))

        # 6. Violations & Inspector Recommendations
        if inspection.violations:
            story.append(Paragraph("Identified Deficiencies & Remedial Action", section_heading))
            viol_data = [
                [
                    Paragraph("<b>Deficiency / Field</b>", bold_label),
                    Paragraph("<b>Severity</b>", bold_label),
                    Paragraph("<b>Statutory Reference</b>", bold_label),
                    Paragraph("<b>Required Remedial Action</b>", bold_label)
                ]
            ]
            for v in inspection.violations:
                sev_color = colors.HexColor("#EF4444") if v.severity == "HIGH" else colors.HexColor("#F59E0B")
                viol_data.append([
                    Paragraph(f"<b>{sanitize_pdf_text(v.field_name.replace('_', ' ').title())}</b>", body_style),
                    Paragraph(f"<font color='{sev_color.hexval()}'><b>{v.severity}</b></font>", body_style),
                    Paragraph(f"<font size=7.5>{sanitize_pdf_text(v.legal_provision or v.rule_id)}</font>", body_style),
                    Paragraph(sanitize_pdf_text(v.recommendation), body_style)
                ])
            viol_table = Table(viol_data, colWidths=[120, 55, 130, 215])
            viol_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#FEE2E2")),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#FCA5A5")),
                ('PADDING', (0, 0), (-1, -1), 3.5),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            story.append(viol_table)
            story.append(Spacer(1, 10))

        # 7. Audit & Pipeline Metadata
        audit_text = (
            f"<b>Pipeline Audit Trace:</b> CV Model: <code>{inspection.cv_model_version or 'YOLO11-CV'}</code> | "
            f"OCR Engine: <code>{inspection.ocr_version or 'PaddleOCR/EasyOCR'}</code> | "
            f"Rule Set: <code>{inspection.rule_set_version or 'LM-2026.1'}</code> | "
            f"Latency: <code>{inspection.processing_time_ms or 0:.0f} ms</code>"
        )
        story.append(Paragraph(audit_text, subtitle_style))
        story.append(Spacer(1, 6))

        # 8. Statutory Legal Disclaimer
        disclaimer_box = [
            [
                Paragraph(
                    "<b>STATUTORY LEGAL DISCLAIMER:</b> AI-assisted screening result. Final legal determination "
                    "requires verification by an authorized inspector/competent authority under the Legal Metrology Act, 2009 "
                    "and Legal Metrology (Packaged Commodities) Rules, 2011. This automated screening does not replace official statutory certification.",
                    disclaimer_style
                )
            ]
        ]
        disc_table = Table(disclaimer_box, colWidths=[520])
        disc_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#94A3B8")),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(disc_table)

        doc.build(story, canvasmaker=NumberedCanvas)
        logger.info(f"Generated PDF audit report at: {output_path}")
        return output_path

def generate_pdf_report(inspection: Inspection, output_path: Optional[str] = None) -> str:
    return CompliancePDFReportGenerator.generate(inspection, output_path)
